target: possion_3d
n_samps_domain: 1000000
n_samps_bc: 1000000
batch_size: 5000
shape_name: tetrahedron
shape_kwargs:
    vertices: [[.23, 0., 0.1], [1., 1., 0.], [0., .92, 0.], [.5, .5, 1.]]
    boundary_type: 'uniform'
